version: "3"
services:
  api:
    build: .
    container_name: api
    env_file:
      - .env
    command: ["./wait-for-it.sh"]
    volumes:
      - .:/code
    depends_on:
      - database
    ports:
      - "5000:5000"
  database:
    image: postgres:10.4
    container_name: database
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=egar
    expose:
      - "5432"
  test_database:
    image: postgres:10.4
    container_name: test_database
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_egar
    expose:
      - "5454"
