"""0002

Revision ID: 1ff2d6f33817
Revises: 0cfa94d960b2
Create Date: 2018-10-02 17:34:31.058660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff2d6f33817'
down_revision = '0cfa94d960b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=130), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisations'))
    )
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=True)
    op.add_column('users', sa.Column('org_owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_org_owner_id_organisations'), 'users', 'organisations', ['org_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_org_owner_id_organisations'), 'users', type_='foreignkey')
    op.drop_column('users', 'org_owner_id')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
