"""0001

Revision ID: 56e38597b775
Revises: 
Create Date: 2018-09-25 00:06:11.185941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e38597b775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=130), nullable=True),
    sa.Column('uuid', sa.String(length=130), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('usersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=130), nullable=True),
    sa.Column('login_date', sa.DateTime(), nullable=True),
    sa.Column('logout_date', sa.DateTime(), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts_since_last_login', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('login_state', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersession')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
